server:
  host: 0.0.0.0
  port: 8086
  grpc_port: 50060
  read_timeout: 30
  write_timeout: 30

elasticsearch:
  addresses:
    - http://localhost:9200
  indices:
    issues: issues
    projects: projects
    users: users

kafka:
  brokers:
    - localhost:19092
  consumer_group: search-service
