global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8080']

  - job_name: 'org-service'
    static_configs:
      - targets: ['org-service:8080']

  - job_name: 'project-service'
    static_configs:
      - targets: ['project-service:8080']

  - job_name: 'issue-service'
    static_configs:
      - targets: ['issue-service:8080']

  - job_name: 'workflow-service'
    static_configs:
      - targets: ['workflow-service:8080']
